# Python Review

## Libraries and packages

**library:** a collection of code to perform tasks

In [1]:
import numpy as np

## Variables

**variable:** a name we assign to an object

In [2]:
# Assign array to variable a
a = np.array([[1,1,2], [3,5,8]])
a

array([[1, 1, 2],
       [3, 5, 8]])

## Objects

**objects:** bundle of *properties* and *actions* 

Ex.

Object: data frame

Properties: # of rows, # of cols, date created

Actions: Select row, add column

## Types

Every object has a **type**. We can call the **type** or **class**

In [6]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [7]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [9]:
print(a[1,1])

5


## Functions

Functions take in arguement. Optional & required arguments create an output.

In [10]:
# Function help
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

## Attributes & Methods

Objects have attributes and methods

- **attribute**: a property of the object, some piece of information about it

- **method**: a procedure associated with the object, an action stemming from the object

In [14]:
print(a)

# Example attribute 
a.shape
# Example method
a.max()

[[1 1 2]
 [3 5 8]]


8

## Exercise

In [16]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

`sep` argument is an optional argument, we can run `print()` without it and will print the string normally, default is with a space.

In [23]:
var1 = 77
var2 = '99'
print(var1, var2, var1, sep='%')


77%99%77
